server:
  port: 20000

  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: gulimall-authserver-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080

  redis:
    host: 192.168.56.10
    port: 6379

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true


  thymeleaf:
    cache: false

  session:
    store-type: redis


#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'



