spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      sms:
        host: https://fesms.market.alicloudapi.com
        path: /sms/
        skin: 1
        sign: 175622
        appcode: b14f674581e4411c990e18bdfcfc35d6


  application:
    name: gulimall-third-party

server:
  port: 30000